apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: docker.io/camunda/identity:8.4.21
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CAMUNDA_IDENTITY_ZEEBE_GATEWAYADDRESS
              value: "zeebe-gateway:26500"
            - name: CAMUNDA_IDENTITY_ELASTICSEARCH_URL
              value: "[ELASTICSEARCH_URL]"
            - name: CAMUNDA_IDENTITY_ELASTICSEARCH_INDEXPREFIX
              value: "[ELASTIC_INDEX]"
            - name: SPRING_DATASOURCE_URL
              value: "[POSTGRES_URL]"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: identity-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-db-secret
                  key: POSTGRES_PASSWORD
            - name: CAMUNDA_IDENTITY_AUTH_PROVIDER_BACKEND_URL
              value: "[KEYCLOAK_URL]"
          ports:
            - name: http
              containerPort: 8080