apiVersion: apps/v1
kind: Deployment
metadata:
  name: operate
  labels:
    app: operate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operate
  template:
    metadata:
      labels:
        app: operate
    spec:
      containers:
        - name: operate
          image: docker.io/camunda/operate:8.4.20
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS
              value: "zeebe-gateway:26500"
            - name: CAMUNDA_OPERATE_ELASTICSEARCH_URL
              value: "[ELASTICSEARCH_URL]"
            - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
              value: "[ELASTIC_INDEX]"
            - name: SPRING_DATASOURCE_URL
              value: "[POSTGRES_URL]"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: operate-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: operate-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 8080