apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
data:
  application.yaml: |
    spring:
      profiles:
        active: prod
    camunda:
      console:
        zeebe:
          gatewayAddress: zeebe-gateway:26500
        elasticsearch:
          url: "[ELASTICSEARCH_URL]"
          indexPrefix: "[ELASTIC_INDEX]"
        auth:
          provider:
            backend:
              url: "[KEYCLOAK_URL]"
    spring.datasource:
      url: "[POSTGRES_URL]"
      username: "[POSTGRES_USER]"
      password: "[POSTGRES_PASSWORD]"
