apiVersion: v1
kind: Secret
metadata:
  name: web-modeler-db-secret
type: Opaque
stringData:
  POSTGRES_URL: "[POSTGRES_URL]"
  POSTGRES_USER: "[POSTGRES_USER]"
  POSTGRES_PASSWORD: "[POSTGRES_PASSWORD]"
---
apiVersion: v1
kind: Secret
metadata:
  name: web-modeler-websockets-db-secret
type: Opaque
stringData:
  POSTGRES_URL: "[POSTGRES_URL]"
  POSTGRES_USER: "[POSTGRES_USER]"
  POSTGRES_PASSWORD: "[POSTGRES_PASSWORD]"