apiVersion: v1
kind: Service
metadata:
  name: zeebe-broker
  labels:
    app: zeebe-broker
spec:
  ports:
    - name: command
      port: 26501
      targetPort: command
    - name: internal
      port: 26502
      targetPort: internal
  selector:
    app: zeebe-broker
