apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  password: "[KEYCLOAK_ADMIN_PASSWORD]"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "[POSTGRES_USER]"
  POSTGRES_PASSWORD: "[POSTGRES_PASSWORD]"
