apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist
  labels:
    app: tasklist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasklist
  template:
    metadata:
      labels:
        app: tasklist
    spec:
      containers:
        - name: tasklist
          image: docker.io/camunda/tasklist:8.7.13
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS
              value: "zeebe-gateway:26500"
            - name: CAMUNDA_TASKLIST_ELASTICSEARCH_URL
              value: "[ELASTICSEARCH_URL]"
            - name: CAMUNDA_TASKLIST_ELASTICSEARCH_INDEXPREFIX
              value: "[ELASTIC_INDEX]"
            - name: SPRING_DATASOURCE_URL
              value: "[POSTGRES_URL]"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: tasklist-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tasklist-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 8080